provider:
  default:
    language: 8.0

sources:
  - "**/*.cs"

binaries:
  - out/web.dll
  - out/web.runtimeconfig.json

environment:
  ASPNETCORE_URLS: http://*:3000
  COMPlus_TieredCompilation: 1

deps:
  - aspnetcore-runtime-3.1

command: /opt/web/out/web.dll
