framework:
  website: rapidoid.org
  version: 5.5

build:
  - mvn compile assembly:single -q

binaries:
  - target/server-1.0.0-jar-with-dependencies.jar

command: >
  /usr/bin/java -server
  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts  -cp /opt/web/target/server-1.0.0-jar-with-dependencies.jar
  benchmark.rapidoid.Main profiles=production
