framework:
  website: coastonclojure.com
  version: 1.0

files:
  - "src/**/*.clj"
  - deps.edn

environment:
  COAST_ENV: prod

binaries:
  - coast.jar

command: /usr/bin/java -jar /opt/web/coast.jar 3000
