framework:
  website: actframework.org
  version: 1.9

build:
  - mvn package
  - mv target/dist/server-1.0.0-*.tar.gz target/dist/server-1.0.0.tar.gz

binaries:
  - target/dist/server-1.0.0.tar.gz

bootstrap:
  - tar -xvzf target/dist/server-1.0.0.tar.gz

command: /opt/web/run
