framework:
  website: struts.apache.org
  version: 2.5

build:
  - mvn clean package

binaries:
  - target/server-1.0.0-standalone.jar

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/server-1.0.0-standalone.jar --port 3000
