framework:
  website: javalin.io
  version: 3.9

build:
  - mvn compile assembly:single

binaries:
  - target/server-1.0.0-jar-with-dependencies.jar

command: >
  /usr/bin/java -server  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts  -cp
  /opt/web/target/server-1.0.0-jar-with-dependencies.jar benchmark.javalin.Bench
  profiles=production
