framework:
  website: spring.io/projects/spring-framework
  version: 5.2

build:
  - mvn clean package

binaries:
<<<<<<< HEAD
  - target/server-1.0.0.war
  - target/server-1.0.0/WEB-INF/lib/jetty-runner-9.4.30.v20200611.jar
=======
  - target/server-1.0.0/WEB-INF/lib/jetty-runner-9.4.30.v20200611.jar
  - target/server-1.0.0.war
>>>>>>> 45c4a9d6... chore(java): Standardize binary name

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/server-1.0.0/WEB-INF/lib/jetty-runner-9.4.30.v20200611.jar --port 3000 /opt/web/target/server-1.0.0.war
