framework:
  website: lets-blade.com
  version: 2.0

build:
  - mvn compile assembly:single -q

binaries:
  - target/server-1.0.0-jar-with-dependencies.jar

command: /usr/bin/java -jar /opt/web/target/server-1.0.0-jar-with-dependencies.jar
