framework:
  website: jooby.io
  version: 2.8

build:
  - mvn clean package

binaries:
  - target/server.jar

command: >
  /usr/bin/java -server
  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -XX:-UseBiasedLocking -XX:+UseStringDeduplication
  -jar /opt/web/target/server.jar benchmark.App
